from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: TEST 1
    Package: TestProject.Generated.Tests.TEST1
    Test: TEST AIRBNB 3
    Generated by: Cương Khuất Nguyên (knc.uetvnu@gmail.com)
    Generated on 11/16/2022, 19:20:16
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="fHeD9xlz_iShr2Xazft8M0EOBqWCf0RpG0s-az1c-Kk",
                              project_name="TEST 1",
                              job_name="TEST AIRBNB 3")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://www.airbnb.com.vn/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'svg'
    try:
        svg = driver.find_element(By.XPATH,
                                  "//section/div/div/div[2]/div/div[1]//*[name()='svg']")
        svg.click()
    except Exception:
        # Failure Behaviour: Continue
        pass

    # 3. Click 'Địa điểm bất kỳ'
    _a_i_m_b_t_k_ = driver.find_element(By.XPATH,
                                        "//div[. = 'Địa điểm bất kỳ']")
    _a_i_m_b_t_k_.click()

    # 4. Click 'DIV'
    div = driver.find_element(By.XPATH,
                              "//div/div[2]/div/button/div")
    div.click()

    # 5. Click '25'
    _25 = driver.find_element(By.XPATH,
                              "//td[5]/div[. = '25']")
    _25.click()

    # 6. Click '17'
    _17 = driver.find_element(By.XPATH,
                              "//td[6]/div[. = '17']")
    _17.click()

    # 7. Click 'Thêm khách'
    th_m_kh_ch = driver.find_element(By.XPATH,
                                     "//div[2][. = 'Thêm khách']")
    th_m_kh_ch.click()

    # 8. Click 'SPAN2'
    span2 = driver.find_element(By.XPATH,
                                "//div[1]/div[2]/div/button[2]/span")
    span2.click()

    # 9. Click 'SPAN2'
    span2 = driver.find_element(By.XPATH,
                                "//div[1]/div[2]/div/button[2]/span")
    span2.click()

    # 10. Click 'SPAN2'
    span2 = driver.find_element(By.XPATH,
                                "//div[1]/div[2]/div/button[2]/span")
    span2.click()

    # 11. Click 'SPAN3'
    span3 = driver.find_element(By.XPATH,
                                "//div[3]/div[2]/div/button[2]/span")
    span3.click()

    # 12. Click 'SPAN3'
    span3 = driver.find_element(By.XPATH,
                                "//div[3]/div[2]/div/button[2]/span")
    span3.click()

    # 13. Click 'SPAN4'
    span4 = driver.find_element(By.XPATH,
                                "//div[2]/div[2]/div/button[2]/span")
    span4.click()

    # 14. Click 'SPAN4'
    span4 = driver.find_element(By.XPATH,
                                "//div[2]/div[2]/div/button[2]/span")
    span4.click()

    # 15. Click 'svg3'
    svg3 = driver.find_element(By.XPATH,
                               "//div[4]/div[2]/div/button[2]//*[name()='svg']")
    svg3.click()

    # 16. Click 'SPAN'
    span = driver.find_element(By.XPATH,
                               "//div[5]/div[1]/div[3]/button/span/span")
    span.click()

    # 17. Click 'Bộ lọc'
    b_l_c = driver.find_element(By.XPATH,
                                "//button[. = 'Bộ lọc']")
    b_l_c.click()

    # 18. Click 'SPAN5'
    span5 = driver.find_element(By.XPATH,
                                "//div[2]/div/div[1]/div[2]/div[2]/div[1]//span")
    span5.click()

    # 19. Click 'Toàn bộ nhà'
    to_n_b_nh_ = driver.find_element(By.CSS_SELECTOR,
                                     "#filterItem-6707675653813756165-checkbox-room_types-Entire_home_apt-row-checkbox")
    to_n_b_nh_.click()

    # 20. Click 'Hiển thị 828 nhà'
    hi_n_th_828_nh_ = driver.find_element(By.XPATH,
                                          "//a[. = 'Hiển thị 828 nhà']")
    hi_n_th_828_nh_.click()
